//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerContacts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public int contact_id { get; set; }
        public string contact_name { get; set; }
        public string contact_email { get; set; }
        public string contact_number { get; set; }
        public int customer_id { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
